### ISSUE TITLE
[Feature Request] Debrid services (cloud cache checking, adding magnet/torrent to debrid service)

### ISSUE THREAD

**Issue by morpheasgr** [itszechs/TorrentiumApp#1]
Greetings, just stumbled upon this app randomly while searching for an Rclone client for Android (since RCX seems to be abandoned). While this app is completely different, I really like your idea, and would like to request the addition of debrid services that offer remote torrenting and a shared cache, to be added as a 'proxy'.

All debrid providers have an API to control their seedbox, the ones I am interested to see implemented are:

Debrid-Link.fr: https://debrid-link.fr/api_doc/v2/introduction

AllDebrid:
https://docs.alldebrid.com/#general-informations

and

Real-Debrid:
https://api.real-debrid.com/

By the way I used to own and had donated to an app called Torrentium on the Google Play store, but I thought it was abandoned.
It was kinda simplistic but had support for one of these debrid services.

PS: can arrange for you to get temporary api keys for testing, for the first two and probably for the third.

Check it out:

https://play.google.com/store/apps/details?id=com.yablio.torrentium

**Comment by itsZECHS** [comment]
> request the addition of debrid services that offer remote torrenting and a shared cache, to be added as a 'proxy'

So, what you're suggesting is adding support for seedboxes & real debrid so they can be used as a source for downloading instead of aria2c (the one that's currently being used in the backend), is that correct?

Sure, that sounds great, as long as they have a public api.

With that being said, I already have 3 updates planned so this won't be a priority for a while, which is fine as I'm hoping to receive request for more seedboxes support as I've little to no knowledge about them I don't know which ones to include in initial release.

P.S I looked over the ones you mentioned and they all are easy to implement so that won't be a problem

> donated to an app called Torrentium on the Google Play

I never uploaded this app to Google Play or plan to (as I'm sure it violates several ToS). 

> https://play.google.com/store/apps/details?id=com.yablio.torrentium

I'm not affiliated with them.

**Comment by itszechs** [comment]
I'm sorry, but this feature doesn't fit the scope of this project.
